### ISSUE TITLE
Can't use GCP Cloud SQL connection string with native PostgresSettings

### ISSUE THREAD

**Issue by rodrigoalmeida94** [developmentseed/tifeatures#32]
When using GCP database instances with Cloud Run functions, the connection string of the database includes unix sockets, i.e.:
```
postgresql://cerulean-cloud-test-database:APASSWORD@/SOMEDB?host=/cloudsql/SOME-PROJECT:europe-west1:SOME-INSTANCE-af6e417
```

Passing this as `DATABASE_URL` returns a validation error coming from Pydantic.PostgresDsn - https://github.com/developmentseed/tifeatures/blob/257246a6fdc426fcc10b02decfde8812f396a158/tifeatures/settings.py#L71. 
This has been discussed [upstream](https://github.com/samuelcolvin/pydantic/issues/960) and more recently [here](https://github.com/samuelcolvin/pydantic/issues/3900), and looks like this won't be addressed any time soon. Since https://github.com/MagicStack/asyncpg/issues/419 AsyncPg supports these types of connection string.

The way I got around this now is defining my own `PostgresSettings` class, removing the pydantic validation all together. This is fine but I'm wondering if it could make sense to add an extra env var like `TIFEATURES_CLOUDSQL` which we could set to True, and then that would bypass the pydantic validation?

Thanks!

**Comment by vincentsarago** [comment]
Thanks for opening the issue @rodrigoalmeida94 

> This is fine but I'm wondering if it could make sense to add an extra env var like TIFEATURES_CLOUDSQL which we could set to True, and then that would bypass the pydantic validation?

I kinda don't really like adding something specific for Cloud provider use case, and would prefer if we can push the fix upstream or do like you do: customize your own application!

**Comment by rodrigoalmeida94** [comment]
Perfect, makes sense to me!
