### ISSUE TITLE
Add additional types to dbmodel

### ISSUE THREAD

**Issue by abarciauskas-bgse** [developmentseed/tifeatures#56]
While creating data for EIS Fire project (see https://github.com/NASA-IMPACT/veda-features-api/pull/10) Alexey noticed that the queryables endpoint for the fire perimeter data is returning strings for. many of the fields (see https://sbbj812m1j.execute-api.us-west-2.amazonaws.com/collections/public.eis_fire_perimeter/queryables).

I inspected the table schema and found the data is stored in the database correctly, i.e.:

```python
from sqlalchemy import text
engine = create_engine(f"postgresql://{username}:{password}@{host}:5432/{database}")  
sql = text("""
SELECT 
   table_name, 
   column_name, 
   data_type 
FROM 
   information_schema.columns
WHERE 
   table_name = 'eis_fire_perimeter';
""")
result = engine.execute(sql)
result.fetchall()
```

returns

```python
[('eis_fire_perimeter', 'ogc_fid', 'integer'),
 ('eis_fire_perimeter', 'n_pixels', 'bigint'),
 ('eis_fire_perimeter', 'n_newpixels', 'bigint'),
 ('eis_fire_perimeter', 'farea', 'double precision'),
 ('eis_fire_perimeter', 'fperim', 'double precision'),
 ('eis_fire_perimeter', 'flinelen', 'double precision'),
 ('eis_fire_perimeter', 'duration', 'double precision'),
 ('eis_fire_perimeter', 'pixden', 'double precision'),
 ('eis_fire_perimeter', 'meanfrp', 'double precision'),
 ('eis_fire_perimeter', 't', 'character varying'),
 ('eis_fire_perimeter', 'fid', 'bigint'),
 ('eis_fire_perimeter', 'wkb_geometry', 'USER-DEFINED')]
```

so I looked at the tifeatures code and found that the types above are not included in dbmodel.py: https://github.com/developmentseed/tifeatures/blob/957ae94fbaa2ffabc8ceba9215227abb1e2406aa/tifeatures/dbmodel.py#L24-L31

**Proposed solution:**

Could we add to that conditional:

```python
        if any(
            [
                pgtype.startswith("int"),
                pgtype.startswith("num"),
                pgtype.startswith("float"),
                pgtype.startswith("double"),
                pgtype.startswith("bigint"),
            ]
        ):
            return "number"
```

**Comment by abarciauskas-bgse** [comment]
@vincentsarago @bitner let me know what you think of ⬆️ - I understand y'all are working on https://github.com/developmentseed/tipg so not sure if this should distract from that.

**Comment by abarciauskas-bgse** [comment]
This may require another issue for `t` - `t` is a datetime object and is stored as `character varying` in the DB table, so this may be an issue of converting / casting that to a datetime during insert. If you all have insight into that, that would be appreciated.

**Comment by vincentsarago** [comment]
>This may require another issue for t - t is a datetime object and is stored as character varying in the DB table, so this may be an issue of converting / casting that to a datetime during insert. If you all have insight into that, that would be appreciated.

There are 2 issues:
- `issue of converting / casting that to a datetime during insert`
- in https://docs.ogc.org/DRAFTS/19-079r1.html#filter-queryables type are defined to be only `number`, `array` `boolean`, `object` or `string`

**Comment by bitner** [comment]
As @vincentsarago said, the types that we are listing as the json type for queryables are limited to the basic json data types (number, array, boolean, object, string).

This means we always are dealing with three different typing systems which don't quite overlap perfectly. Python types, PostgreSQL types, and JSON types (which is what we report in Queryables).
